### PR TITLE
replace `$OSTYPE` with `uname -s`

### PR DESCRIPTION
**Pull request by retokromer**
resolves https://github.com/mediamicroservices/mm/issues/172

### CODE REVIEW

**Comment by dericed** [comment]
expression needs a double quote, but that issue was there before too, so i'll merge for now

**Comment by retokromer** [comment]
@dericed You mean `$(uname -s)`? It’s a system function, but I’m happy to quote here and the other in the config file.

**Comment by dericed** [comment]
if `$(uname -s)` resulted in a phrase with a space, i think it would break the equation. `"$(uname -s)"` is safer. untested and commented with some guessing

**Comment by retokromer** [comment]
It’s resolved in https://github.com/mediamicroservices/mm/pull/175 and https://github.com/mediamicroservices/mm/pull/176.

**Pull request merged**
