### PR TITLE
add check for modification

### PR DESCRIPTION
**Pull request by privatezero**
This should resolve https://github.com/mediamicroservices/mm/issues/117 using the comparison of modification time to current time.

### CODE REVIEW

**Comment by dericed** [comment]
Did you test this? Just curious if the timing is ok, or if many files would get through when their mod time is 1 second less than the current time but still being modified.

**Comment by privatezero** [comment]
I tested it by pointing it at a copy of a large media file that didn't exist yet, starting to create the copy and then running ingestfile before the copy was finished being created.  It was working in that context, but I suppose that only tests for something actively being modified.

**Comment by dericed** [comment]
in that case, LGTM

**Comment by privatezero** [comment]
cool! I'll merge it in!

**Pull request merged**
