### PR TITLE
added in option for LTO_MD5_FLAGS

### PR DESCRIPTION
**Pull request by BleakleyMcD**
Helpful for users that want a different .md5 file than that currently specified in writelto

### CODE REVIEW

**Comment by BleakleyMcD** [comment]
One problem is that I don't know how to set a default value for {LTO_MD5_FLAGS} and so if it isn't set in mmconfig writelto in ltopers will fail when it hits the readback checksum part because the -exec in `find "${TAPE_PATH}" -type f ! -name .DS_Store -exec "${LTO_MD5_FLAGS}"` will be null. So, either there is a default value added into mmconfig, which I'm not sure how to do or writelto is made to exit if `"${LTO_MD5_FLAGS}"` is null...

**Comment by BleakleyMcD** [comment]
oh, maybe the default can be specified as so:

`LTO_MD5_FLAGS.default = md5deep -rel
${LTO_MD5_FLAGS} = LTO_MD5_FLAGS.default`

??

**Comment by BleakleyMcD** [comment]
@dericed

**Comment by dericed** [comment]
You could set a default value for LTO_MD5_FLAGS in the script before the configuration file is read so that it's there and then the config version could just overwrite that if specified.

**Comment by BleakleyMcD** [comment]
I assume the script you mean is `writelto`?

I can't locate where it is reading the config file :(

**Comment by retokromer** [comment]
There is no specific config file for `writelto` and I would not suggest to add one. I guess you should use the `mmfunctions` [config file](https://github.com/mediamicroservices/mm/blob/master/mmfunctions#L4).

**Comment by BleakleyMcD** [comment]
This needs to be merged for the latest ltopers updates to work properly.

**Comment by retokromer** [comment]
@BleakleyMcD I have no merging rights on this repository.

**Comment by BleakleyMcD** [comment]
@dericed :)

**Pull request merged**
