### PR TITLE
Checksumpackage cleanup

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dericed** [comment]
requires change from `md5deep` dependency to `hashdeep` dependency in https://github.com/dericed/homebrew-mm/blob/master/mm.rb

**Comment by privatezero** [comment]
Took a stab at resolving conflicts!

**Comment by privatezero** [comment]
Looks good I think!

**Comment by dericed** [comment]
LGTM, but needs an update to mm.rb

**Comment by privatezero** [comment]
Coo! I'll merge and update the formula!

**Pull request merged**
